spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/spring_chat?authSource=admin

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB

kakaopay:
  cId: ${KAKAOPAY_CID}
  secretKey: ${KAKAOPAY_SECRET_KEY}