spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    moongodb:
      host: mongo
      port: 27017
      database: spring_chat
      username: root
      password: example
      authentication-database: admin

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

kakaopay:
  cId: ${KAKAOPAY_CID}
  secretKey: ${KAKAOPAY_SECRET_KEY}